### ISSUE TITLE
I'm stupid, please help

### ISSUE THREAD

**Issue by Memer56** [Hugo4IT/CheatCoder#1]
I believe I have set it all up right so I don't know if I'm just stupid, but how do I actually input the cheat code? I don't understand where I actually type it. Please help I'm useless.

**Comment by Hugo4IT** [comment]
If you have a CheatCodeListener node anywhere in your scene all you have to do is press the right buttons in order, there's no specific input field, just press the buttons

I hope that clears things up, it works like how cheat-codes used to work back in the day

**Comment by Memer56** [comment]
Thanks for the help!
