### ISSUE TITLE
[feature] Cheatcode Cooldown

### ISSUE THREAD

**Issue by nekocarpet** [Hugo4IT/CheatCoder#3]
Hi, I'm working on an application that is designed to run over a long time. Thought it would be fun to implement an easter egg that triggers on the Konami code.

Since the app won't be restarted, the code needs to be able to repeat-able, which is why I did this https://github.com/Hugo4IT/CheatCoder/pull/2

I thought it would be useful if a cooldown can be implemented as well, so that the code cannot be spammed to spawn an abundance of particles that slows the process down.

I made a shabby workaround in my project using timers and signals, which basically toggles the `disabled` property of CheatCodeListener. This would be another Pull Request if my codes aren't everywhere ;p

**Comment by Hugo4IT** [comment]
Interesting idea! I'll try to implement it when I have the time, I'm currently a bit busy with school but I'll let you know when it's ready :)

**Comment by Hugo4IT** [comment]
Cooldown added ✅
